### ISSUE TITLE
updatedAt not set before saving

### ISSUE THREAD

**Issue by ColonelJ** [DODOEX/dodoex_v2_subgraph#1]
https://github.com/DODOEX/dodoex_v2_subgraph/blob/72f60e258563185e33c42d76ff773d0d1bcfbd37/src/mappings/dodoex/poolFactory.ts#L174-L175

`pair.updatedAt` should be set before doing `pair.save()`!  Some pools have `null` as `updatedAt` because of this.

**Comment by AutarkXu** [comment]
fixed,thank you
