### ISSUE TITLE
Regression constants (B0 and Q0) not present in subgraph API

### ISSUE THREAD

**Issue by mdeib** [DODOEX/dodoex_v2_subgraph#2]
I am trying to get the Base token regression constant (B_0) and the Quote token regression constant (Q_0) of a pool at a given block, but they do not seem to be present under the "pairs" root of the subgraph, despite the other necessary parameters (B, Q, i, k) being present there. I have looked through the code and they are indeed part of the PMM state, but do not seem to be referenced under any of the subgraph's event updates or correspond to any of "pair"'s attributes. Were they erroneously ommited or is there some reason they are not present here?

https://github.com/DODOEX/dodoex_v2_subgraph/blob/72f60e258563185e33c42d76ff773d0d1bcfbd37/generated/DPPFactory/DPP.ts#L161

**Comment by AutarkXu** [comment]
It is because B0 and Q0 are used by token swap in the contract, and the contract provides encapsulated function, so we did not record B0 and Q0 here.

**Comment by mdeib** [comment]
I don't think this solves my particular issue. To be clear I am trying to calculate how much of a token I could have gotten out using dodov2 pools with historical data pulled from this subgraph. Unless I am able to make such a calculation with only the fields currently under "pools" in the subgraph? i.e can I calculate the amount of a token I would have gotten out for any input with only i, k, b and q (and then b0 and q0 can be derived from those others or aren't actually needed)? If I can't then I would need access to these values for this use case. Thanks

**Comment by AutarkXu** [comment]
When using B0 and Q0 to calculate the tokens exchanged, it is necessary to implement the PMM algorithm in your code, so the subgraph does not consider putting B0 and Q0 into the data when recording. To obtain the tokens that can be exchanged out when specified blocks, we prefer to call the archive node directly

**Comment by mdeib** [comment]
I have implemented the PMM algorithm locally from the whitepaper and this code repo and am now attempting to do some historical analysis on the trades. Calling an archive node for all of these analysis requests would be prohibitively expensive, and would not allow me to experiment with my version of the PMM algorithm.

Besides, the same archive node argument could be made for the actual reserves or other PMM parameters too, so why do we need a subgraph at all then? All a subgraph is really doing is making information from an archive node more accesible - I don't see any reason why B0 and Q0 should be excluded?

**Comment by AutarkXu** [comment]
Well, brother, because B0 and Q0 are not used in the data requirements of our products at present, there is no tracking of the two parameters in subgraph. If you have such requirements, we can add them.

**Comment by mdeib** [comment]
I do have such requirements, so if they could be added the the official dodoex subgraph that would be appreciated, thanks!
